---
dependency:
  name: galaxy
  options:
    role-file: molecule/os_hardening/requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: "generic/${MOLECULE_DISTRO}"
    memory: 1024
    cpus: 2
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
